# .github/workflows/actions.yml
---
name: CI/CD
on: push
jobs:
  build:
    runs-on: ex-ci-runner
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm clean-install
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: app
          path: |
            dist
            package*.json
  deploy:
    needs:
      - build
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ex-cd-runner
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app
      - run: /ex-app/deploy.sh team1
